#pragma once

#define STR_IN_NOTTEXT				L""
#define STR_IN_WINDOW_TITLE			L"DSO Launcher"
#define STR_IN_CUR_FILE				L"Current file:"
#define STR_IN_FULL_INSTALL			L"Overall progress"
#define STR_IN_READY_INSTALL		L"Preparing to Install"
#define STR_IN_UPDATE				L"Ready to update"
#define STR_IN_START				L"Preparing to run"
#define STR_IN_INSTALL				L"Installing files"
#define STR_IN_PACK					L"Packing file"
#define STR_IN_FILE_CHECK			L"Checking files"
#define STR_IN_CHECK				L"Under maintenance"
#define STR_IN_DOWN					L"File download"
#define STR_IN_GAME_PATH			L"Select the directory where the game installation file will be downloaded"
#define STR_IN_RETRY				L"      Retry [%dtimes]"
#define STR_IN_SUCCESS_INSTALL		L"Game installation is complete"
#define STR_IN_SUCCESS_UPDATE		L"Game update complete"
#define	STR_IN_OFFLINE				L"Your Internet connection has been lost."
#define STR_IN_ISEXECUTE			L"The game is already running."
#define RUN_FAIL					L"Parameter Error"
#define USERTYPE_ERROR				L"Invalid user type"
#define SERVER_ERROR				L"Invalid server type"
#define UNZIP_FILE_OPEN_ERROR		L"Failed to open the compressed file. Please restart the launcher (%s)"
#define UNZIP_ERROR					L"Failed to decompress the compressed file. Please restart the launcher (%s)"

#define ERROR_FULL_CLIENT_NO_EXE	L"Installation files do not exist on the server."
#define STR_ALREADY_START			L"The game launcher is already running."
#define STR_DO_EXIT_GAME			L"Please close Digimon Masters Online first and run it."

#define STR_IN_STARTPAGE_OUR		L"Select game to start page"
#define STR_IN_STARTPAGE_NAVER		L"Naver as the start page"

#define STR_MESSAGE_INSTALL_URL				L"The game is not installed. Please download and install the game installation file."
#define STR_MESSAGE_START_WEB				L"Please run the game from the homepage."
#define STR_MESSAGE_NOT_INSTALL				L"The game is not installed."
#define STR_MESSAGE_CANCEL					L"Installation was canceled."
#define STR_MESSAGE_NO_EXE					L"Executable does not exist."

#define STR_ERROR							L"Launcher Error"
#define STR_FAIL_VERSION_CHECK				L"Error checking launcher version.\nPlease try again."
#define STR_FAIL_PACKER_DOWNLOAD			L"Failed to download UpdateManager.exe file.\nPlease try again."
#define STR_FAIL							L"failure"
#define STR_FAIL_PACK						L"Packing Failed"
#define STR_FAIL_START						L"Please run it after logging in from the web."	
#define STR_FAIL_LINK						L"Shortcut Creation Failed"
#define STR_FAIL_THREAD						L"Failed to create thread"
#define STR_FAIL_INSTALL					L"Exceeded file installation count: (Error number:%ld)"
#define STR_FAIL_CONNECT_INTERNET			L"Internet connection failed"
#define STR_FAIL_CONNECT_FILE_SERVER		L"Failed to access server file:%s"
#define STR_FAIL_CONNECT_SERVER				L"%sFile Access Failed: Unknown error (error number:%ld)"
#define STR_FAIL_PATCHINFO					L"Failed to get patch information."
#define STR_FAIL_CLIENT_PATCHINFO			L"Patch information does not exist in the client."
#define STR_FAIL_DOWNSDK					L"Download SDK Error"
#define STR_FAIL_DISK						L"Insufficient disk space for game installation. (Please secure 5GB or more disk space)"
#define STR_FAIL_LAUNCHER_REG				L"The launcher path set in the registry does not exist. Please install the launcher manually."
#define STR_FAIL_GAME_REG					L"The game installation path does not exist in the registry."
#define STR_FAIL_PATCHINFO_OLD				L"The version on the client is too old. : Please reinstall the game or patch manually"
#define STR_FAIL_PATCHINFO_CLIENT			L"The version information on the client is corrupted: Please reinstall the game or patch manually."
#define STR_FAIL_EXEFILE_VERSION			L"The executable file version is different. Run the game launcher again."

#define STR_PLAYGAME_ERROR_FILE_NOT_FOUND		L"Error starting game: Executable file does not exist. Please try later."
#define STR_PLAYGAME_ERROR_PATH_NOT_FOUND		L"Error starting the game: The path is incorrect."
#define STR_PLAYGAME_ERROR_NOT_ENOUGH_MEMORY	L"Game start error: Out of memory."
#define STR_PLAYGAME_ERROR_BAD_EXE_FORMAT		L"Game start error: The executable file is invalid."
#define STR_PLAYGAME_ERROR_DEFAULT				L"Game start error: number%ld"

#define STR_PACKER_ERRO_DEFAULT					L"Launcher patch error: number%ld"

#define STR_FAIL_RUN_EXEFILE					L"Visual C++ Redistributable for Visual Studio 2015 (x86) installation files are missing."

#define STR_DIGIMONMASTERS_KOR			L"Digital Shinka"
#define STR_DIGIMONRPG_KOR				L"Digimon RPG"
#define STR_NOIR_KOR					L"Noir Online"

#define STR_DIGIMONMASTERS_ENG			L"Digital Shinka"
#define STR_DIGIMONRPG_ENG				L"DigimonRPG"
#define STR_NOIR_ENG					L"Noir"

#define STR_BUTTON_HOMEPAGE				L"Homepage"
#define STR_BUTTON_PATCH				L"Game News"
#define STR_BUTTON_OPTION				L"Option"
#define STR_BUTTON_OK					L"Check"
#define STR_CLIENT_PATH_NUMBER			L"Client Path Number :%d"
